name: Publish to PyPI

on:
 push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # 第二步：打包构建
    - name: Build
      uses: actions/setup-node@master
    - run: npm install npm@latest -g 
    - run: npm init -y
    - run: npm install # 安装第三方包
    - run: npm cache clean --force 
    - run: npm run build # 打包
    - run: tar -zcvf release.tgz .nuxt static nuxt.config.js package.json package-lock.json pm2.config.json
      # 把.nuxt、nuxt.config.js等文件，打包压缩为release.tgz

    - name: Build and Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.TOKEN }}
      run: |
        python setup.py sdist bdist_wheel
        pip install twine
        twine upload dist/*
