name: Update Pip and Build

on:
  push:
    branches:
      - main  # 修改为您的默认分支


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - name: Upgrade pip
      run: |
        python -m pip install --upgrade pip

    - name: Build and Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPITOKEN }}
      run: |
       
        python setup.py sdist 
        
        pip install twine
     
        python setup.py sdist 

        python setup.py register
         
        twine upload --repository-url https://upload.pypi.org/legacy/ dist/*

        twine upload dist/*  --verbose







