name: Cache Docker Container Build

on:
  push:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build and cache container
        run: |

          docker pull sophgo/tpuc_dev:latest
   
      - name: Run Docker Container and YOLOv5 Test
        run: |
          docker run --privileged --name myname1234 -v $PWD:/workspace sophgo/tpuc_dev:latest bash -c '
      
          source ./envsetup.sh
          ./build.sh
          '
      
          docker build -t myname1234 .
          docker save -o myname1234.tar myname1234

      - name: Save cache
        uses: actions/cache@v2
        with:
          path: /var/lib/docker
          key: ${{ runner.os }}-docker-${{ hashFiles('Dockerfile') }}

 
    
          
          




