name: Publish Release


on:
  push:
    branches:
      - main  # 或者你的默认分支

jobs:
  publish-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

    

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{34}}
          release_name: Release v${{34}}
          draft: false
          prerelease: false
          
      - name: Find PY Files
        id: find_py
        run: |
          find . -type f -name "*.py" -exec echo {} + > py_files.txt
          
        continue-on-error: true

      - name: Read PY File List
        id: read_py_list
        run: |
          cat py_files.txt
          var=$(cat py_files.txt)
          echo ${vars}
         
        continue-on-error: true
      - name: Upload Release Assets
        id: upload_release_assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${var}   # 使用查找的文件列表
          asset_name: py_files.zip  # 上传后的文件名
          asset_content_type: application/zip  # 文件类型
